---

plugins:
  - rubocop-rspec
  - rubocop-performance

inherit_from:
  - https://raw.githubusercontent.com/booch/config_files/master/ruby/rubocop.yml

# Ignore some files. NOTE: Exclude does not add to any existing Exclude directives.
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'vendor/**/*'

# Allow longer lines.
Layout/LineLength:
  Max: 160

# Use `{}` for blocks that return a value; otherwise use `do` and `end`.
# We make a few exceptions, mostly for RSpec. And for grammar and transform rules.
Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - expect
  AllowedMethods:
    - rule
    - rule!
    - let
    - let!
    - subject

Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# Be a bit more lenient with RSpec: don't require filename to match class; allow more than 1 expectation per example.
RSpec/SpecFilePathFormat:
  Enabled: False
RSpec/MultipleExpectations:
  Max: 10
RSpec/ExampleLength:
  Max: 20

RSpec/EmptyLineAfterSubject:
  Enabled: false

Naming/MethodName:
  AllowedPatterns:
    - '\AParser\z'

# Allow rules to use `+` without suggesting string interpolation.
Style/StringConcatenation:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

# Crashes, as of RuboCop 1.74.0.
Style/WordArray:
  Enabled: false

Performance/StringInclude:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false

# Prefer `class X < Data.define(...)` over `X = Data.define(...)`.
# It makes nested constants work as expected.
# See https://allaboutcoding.ghinda.com/more-about-how-to-create-a-data-class-in-ruby for details.
Style/DataInheritance:
  Enabled: false
