name: Specs
on:
  # Run this workflow manually from the Actions tab.
  workflow_dispatch:

  # Run when pushing to `main`.
  push:
    branches:
      - main

  # Run when making a PR against `main`.
  pull_request:
    branches:
      - main

# Set permissions of the GITHUB_TOKEN to allow pushing.
permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
        ruby: ["3.3", "3.4", head, jruby, truffleruby, truffleruby+graalvm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: make test
